Feature/udh 21 standard input fields bestaande component prio1
a-ui/core_branding_scss pull request #211
Opened 2021-09-24 08:59 UTC by Redn4s

2021-09-24 14:13 UTC, TriangleJuice requested changes
Extra opmerking: &quot; mag gewoon " worden

2021-09-24 14:13 UTC, TriangleJuice commented on src/styles/quarks/_quarks.css-properties.scss
> +  --state-danger-light:      var(--danger-400); // TODO: Give --state-danger-light to a better name
// TODO: Use proper spelling for technical debt messages 😁

2021-09-24 14:13 UTC, TriangleJuice commented on src/templates/atoms.njk
> +                        <div class="a-input__info-spacer"></div>
Kunnen we dit vervangen door een flexibele flex-oplossing? Goeie naam voor een Suske en Wiske album trouwens: "De flexibele flex-oplossing"

2021-09-24 14:13 UTC, TriangleJuice commented on src/templates/atoms.njk
> +                        <small class="a-input__character-counter">0 / 200</small>
Jeroen had gevraagd om de counter mee op te nemen in de voorbeelden, maar niet als standaard, dus graag een apart voorbeeld hiervoor en liefst ergens meer onderaan.

2021-09-24 14:13 UTC, TriangleJuice commented on src/templates/atoms.njk
> +                        <small class="a-input__success-text">Success description</small>
Persoonlijk zou ik hier het fysieke icoon gebruiken i.p.v. de "in de code verstopte" versie.

2021-09-24 14:13 UTC, TriangleJuice commented on src/templates/atoms.njk
> +                        <small class="a-input__error-text">Error description</small>
Zelfde opmerking als hierboven.

2021-09-27 09:42 UTC, TriangleJuice requested changes
Good work! Heb nog maar een paar comments 😅

2021-09-27 09:42 UTC, TriangleJuice commented on src/styles/atoms/_atoms.input.scss
> +  flex-shrink: 0;
Minor: liever shorthand `flex` gebruiken.

2021-09-27 09:42 UTC, TriangleJuice commented on src/styles/molecules/_molecules.upload.scss
> +    top: -3px;
Misschien nog upgraden naar rem?

2021-09-27 09:42 UTC, TriangleJuice commented on src/templates/atoms.njk
> +      &lt;span class="ai" aria-hidden="true"&gt;&lt;svg&gt;&lt;use href="https://cdn.antwerpen.be/core_branding_scss/5.0.1/images/ai.svg#ai-triangle" /&gt;&lt;/svg&gt;&lt;/span&gt;
Hier zouden we eens moeten kijken hoe we dat best aanpakken, want in principe werkt dit niet (SVG geeft CORS problemen).

2021-09-29 14:38 UTC, Redn4s commented
> Good work! Heb nog maar een paar comments 😅

De flex shorthand is toegevoegd en de pixel values zijn gewrapped in rem(). Voor die pixel values omzetten naar rem is er nog een algemeen ticket in JIRA. Ik zal dit morgen proberen op te nemen. 🙂 

Voor die CORS issues mbt die SVG's heb ik [een ticket](https://jira.antwerpen.be/browse/UDH-152) aangemaakt. 🙂

2021-09-29 15:55 UTC, TriangleJuice approved these changes

2021-09-30 10:12 UTC, TriangleJuice approved these changes

2021-09-30 12:40 UTC, merged