Avatars
a-ui/core_branding_scss pull request #212
Opened 2021-09-30 08:22 UTC by Redn4s

Bijhorende ticket: https://jira.antwerpen.be/browse/UDH-4

Avatars in buttons volgen nog. 🙂 

<img width="1288" alt="Screenshot 2021-09-30 at 10 22 28" src="https://user-images.githubusercontent.com/4232875/135415416-477b3087-9bd3-467b-a18a-a8e0ec265047.png">

2021-09-30 13:33 UTC, TriangleJuice requested changes

2021-09-30 13:33 UTC, TriangleJuice commented on src/styles/atoms/_atoms.avatar.scss
> +button {
Kunnen deze best niet gescoped worden?

2021-09-30 13:33 UTC, TriangleJuice commented on src/styles/atoms/_atoms.avatar.scss
> +button {
Idem

2021-10-01 06:13 UTC, Redn4s commented on src/styles/atoms/_atoms.avatar.scss
> +button {
Hoe bedoel je juist? 🙂

2021-10-01 07:06 UTC, TriangleJuice approved these changes

2021-10-01 07:26 UTC, merged