Step indicator
a-ui/core_branding_scss pull request #274
Opened 2021-12-16 13:08 UTC by Redn4s

<img width="569" alt="Screenshot 2021-12-16 at 14 07 51" src="https://user-images.githubusercontent.com/4232875/146377584-3be9585d-1ed2-47a1-852d-1e8bfbc116cc.png">

2021-12-17 10:20 UTC, TriangleJuice requested changes
In Safari is er nog een klein bugje dat opgelost wordt door de `<a>` uit de active step te halen (zie ook opmerking semantiek).

2021-12-17 10:20 UTC, TriangleJuice commented on src/styles/molecules/_molecules.step-indicator.scss
> +        }
Volgens mij mag de `<a>` hier semantisch gezien niet staan.

2021-12-17 10:20 UTC, TriangleJuice commented on src/styles/molecules/_molecules.step-indicator.scss
> +    content: counter(steps);
Mooie oplossing!

2021-12-17 15:46 UTC, Redn4s commented
> In Safari is er nog een klein bugje dat opgelost wordt door de `<a>` uit de active step te halen (zie ook opmerking semantiek).

Active step werd verwijderd. Goed gezien! 🙂

2022-01-24 13:57 UTC, TriangleJuice approved these changes

2022-01-24 13:57 UTC, merged